# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-23 16:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20171023_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 23, 16, 37, 46, 145287, tzinfo=utc)),
        ),
    ]
